### ISSUE TITLE
These barely work

### ISSUE THREAD

**Issue by frozen905** [ErcinDedeoglu/proxies#1]
This list must be horrifically out of date.  Of all the proxy lists on GitHub, this is the one with the least working hits.

I got single digit hits with this list after checking over 10,000 entries.

**Comment by ErcinDedeoglu** [comment]
Proxies are automatically checked every 5 minutes before posting. However, there's something you need to know. Most proxies are not installed on dedicated servers, so sometimes they may not be reachable. Proxies work on machines that connect from different locations, such as China, Pakistan, the USA, Vietnam, etc. Some ISP policies may cut off connection requests from different regions, so please consider peak times. Each proxy server has connection limitations, and most of them work on a first-in, first-out strategy.

Also, while working with proxies, I encountered too many strange things. Not every script configuration can connect to every proxy server.

If you don't mind, could you please share the purpose of your code or software configuration that you are using to reach the proxies?

**Comment by MotWnb** [comment]
https://checkerproxy.net/ You can use it to check the list
